# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(500, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\templates\\../img/logo.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btnCloseAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseAbout.setMinimumSize(QtCore.QSize(80, 25))
        self.btnCloseAbout.setMaximumSize(QtCore.QSize(80, 25))
        self.btnCloseAbout.setObjectName("btnCloseAbout")
        self.verticalLayout.addWidget(self.btnCloseAbout, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "About"))
        self.label.setText(_translate("dlgAbout", "Empresa Teis ©"))
        self.label_2.setText(_translate("dlgAbout", " V.0.0.1"))
        self.label_4.setText(_translate("dlgAbout", "Autor: Miguel Rodríguez Quintás"))
        self.btnCloseAbout.setText(_translate("dlgAbout", "OK"))
